print("Enter First Number")
num1 = input()
print("Enter Second Number")
num2 = input()
print("************************************")
print("Sum of Given numbers is : "+str(int(num1)+int(num2)))
print("Difference of Given numbers is : "+str(int(num1)-int(num2)))
print("Product of Given numbers is : "+str(int(num1)*int(num2)))
print("Division of Given numbers is : "+str(int(num1)/int(num2)))
print("************************************")